import OpenAI from 'openai'
import { GoogleGenerativeAI } from '@google/generative-ai'
import type { AppConfig } from './storage'
import type { ClothingItem } from '../types'

async function base64ToFile(dataUrl: string, filename: string): Promise<File> {
  const res = await fetch(dataUrl)
  const blob = await res.blob()
  return new File([blob], filename, { type: blob.type || 'image/jpeg' })
}

async function describePersonWithGemini(profilePhoto: string, apiKey: string): Promise<string> {
  const genAI = new GoogleGenerativeAI(apiKey)
  const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' })
  const base64Data = profilePhoto.includes(',') ? profilePhoto.split(',')[1] : profilePhoto
  const mimeType = profilePhoto.startsWith('data:image/png') ? 'image/png' : 'image/jpeg'
  const result = await model.generateContent([
    { inlineData: { data: base64Data, mimeType } },
    'Describe this person briefly for a fashion illustration: body type, skin tone, hair color and style. Be concise.',
  ])
  return result.response.text()
}

export async function generateOutfitLook(
  items: ClothingItem[],
  profilePhoto: string | null,
  config: AppConfig,
): Promise<string> {
  const outfitDesc = items.map((i) => `${i.name} (${i.color} ${i.category})`).join(', ')

  if (config.provider === 'proxy') {
    const res = await fetch('/api/ai', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        action: 'image-gen',
        items: items.map((i) => ({ name: i.name, color: i.color, category: i.category })),
        profileBase64: profilePhoto ?? undefined,
      }),
    })
    if (!res.ok) throw new Error(`proxy ${res.status}`)
    const { imageBase64 } = await res.json()
    return imageBase64 as string
  }

  if (config.provider === 'gemini') {
    const genAI = new GoogleGenerativeAI(config.apiKey)
    const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash-preview-image-generation' })
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const parts: any[] = []
    // Include item images as visual reference (up to 4)
    for (const item of items.slice(0, 4)) {
      if (item.image?.startsWith('data:')) {
        const base64Data = item.image.split(',')[1]
        const mimeType = item.image.startsWith('data:image/png') ? 'image/png' : 'image/jpeg'
        parts.push({ inlineData: { data: base64Data, mimeType } })
      }
    }
    if (profilePhoto) {
      const base64Data = profilePhoto.includes(',') ? profilePhoto.split(',')[1] : profilePhoto
      const mimeType = profilePhoto.startsWith('data:image/png') ? 'image/png' : 'image/jpeg'
      parts.push({ inlineData: { data: base64Data, mimeType } })
      parts.push({ text: `Generate a realistic full-body fashion photo of this person wearing this outfit: ${outfitDesc}. Preserve the person's exact appearance. Professional studio lighting, clean white background.` })
    } else {
      parts.push({ text: `Create a professional fashion flat-lay photo of these clothing items arranged stylishly: ${outfitDesc}. Clean white background, top-down editorial view, high quality fashion photography.` })
    }
    const result = await model.generateContent({
      contents: [{ role: 'user', parts }],
      generationConfig: { responseModalities: ['IMAGE', 'TEXT'] } as Record<string, unknown>,
    })
    for (const part of result.response.candidates?.[0]?.content?.parts ?? []) {
      const p = part as unknown as Record<string, unknown>
      if (p.inlineData) {
        const d = p.inlineData as { mimeType: string; data: string }
        return `data:${d.mimeType};base64,${d.data}`
      }
    }
    throw new Error('No image generated by Gemini')
  }

  // OpenAI fallback
  const client = new OpenAI({ apiKey: config.apiKey, dangerouslyAllowBrowser: true })
  if (profilePhoto) {
    const imageFile = await base64ToFile(profilePhoto, 'profile.jpg')
    const response = await client.images.edit({
      model: 'gpt-image-1',
      image: imageFile,
      prompt: `Show this person wearing: ${outfitDesc}. Full body, clean white background, professional fashion photo.`,
      size: '1024x1536',
    })
    const b64 = response.data?.[0]?.b64_json
    if (b64) return `data:image/png;base64,${b64}`
  }
  const fallback = await client.images.generate({
    model: 'dall-e-3',
    prompt: `Professional fashion flat-lay photo of outfit: ${outfitDesc}. White background, editorial style, high quality.`,
    size: '1024x1792',
    quality: 'standard',
    n: 1,
  })
  const url = fallback.data?.[0]?.url
  if (!url) throw new Error('No image generated')
  try {
    const imgRes = await fetch(url)
    const blob = await imgRes.blob()
    return await new Promise<string>((resolve) => {
      const reader = new FileReader()
      reader.onload = () => resolve(reader.result as string)
      reader.readAsDataURL(blob)
    })
  } catch {
    return url
  }
}

export async function generateOutfitPreview(
  profilePhoto: string,
  outfitItems: ClothingItem[],
  config: AppConfig
): Promise<string> {
  const outfitDesc = outfitItems.map((i) => `${i.name} (${i.color} ${i.category})`).join(', ')

  if (config.provider === 'gemini') {
    const personDesc = await describePersonWithGemini(profilePhoto, config.apiKey)
    const genAI = new GoogleGenerativeAI(config.apiKey)
    const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash-preview-image-generation' })
    const base64Data = profilePhoto.includes(',') ? profilePhoto.split(',')[1] : profilePhoto
    const mimeType = profilePhoto.startsWith('data:image/png') ? 'image/png' : 'image/jpeg'
    const result = await model.generateContent({
      contents: [{
        role: 'user',
        parts: [
          { inlineData: { data: base64Data, mimeType } },
          { text: `Generate a full-body fashion photo of a person matching this description: ${personDesc}. They are wearing: ${outfitDesc}. Style: editorial fashion photography, clean white background, professional lighting.` },
        ],
      }],
      generationConfig: { responseModalities: ['IMAGE', 'TEXT'] } as Record<string, unknown>,
    })
    for (const part of result.response.candidates?.[0]?.content?.parts ?? []) {
      const p = part as unknown as Record<string, unknown>
      if (p.inlineData) {
        const d = p.inlineData as { mimeType: string; data: string }
        return `data:${d.mimeType};base64,${d.data}`
      }
    }
    throw new Error('No image generated by Gemini')
  }

  // OpenAI: use gpt-image-1 edit with actual person photo for realistic try-on
  const client = new OpenAI({ apiKey: config.apiKey, dangerouslyAllowBrowser: true })
  const imageFile = await base64ToFile(profilePhoto, 'profile.jpg')

  const response = await client.images.edit({
    model: 'gpt-image-1',
    image: imageFile,
    prompt: `Show this exact person wearing this complete outfit: ${outfitDesc}. Full body fashion photo, clean white background, professional studio lighting, photorealistic.`,
    size: '1024x1536',
  })

  const b64 = response.data?.[0]?.b64_json
  if (b64) return `data:image/png;base64,${b64}`

  // Fallback to DALL-E 3 if gpt-image-1 unavailable
  const fallback = await client.images.generate({
    model: 'dall-e-3',
    prompt: `Full-body fashion photo of a person. Outfit: ${outfitDesc}. Style: editorial fashion photography, clean white background, professional lighting, photorealistic.`,
    size: '1024x1792',
    quality: 'standard',
    n: 1,
  })
  const tempUrl = fallback.data?.[0]?.url
  if (!tempUrl) return ''
  // Fetch and convert to base64 so the image doesn't expire
  try {
    const res = await fetch(tempUrl)
    const blob = await res.blob()
    return await new Promise<string>((resolve) => {
      const reader = new FileReader()
      reader.onload = () => resolve(reader.result as string)
      reader.readAsDataURL(blob)
    })
  } catch {
    return tempUrl // fallback to URL if fetch fails
  }
}
